server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /users {
        proxy_pass http://${BACKEND_IP}:8001;
    }

    location /auth {
        proxy_pass http://${BACKEND_IP}:8001;
    }

    location /admin {
        proxy_pass http://${BACKEND_IP}:8001;
    }

    location /events {
        proxy_pass http://${BACKEND_IP}:8002;
    }

    location /registrations {
        proxy_pass http://${BACKEND_IP}:8003;
    }

    location /notifications {
        proxy_pass http://${BACKEND_IP}:8004;
    }
}
